"""Constants and presets for slide-printer."""

from typing import Dict, Tuple

# Standard paper sizes in points (1 pt = 1/72 inch)
PAPER_SIZES: Dict[str, Tuple[float, float]] = {
    "a4": (595.28, 841.89),
    "letter": (612.0, 792.0),
    "legal": (612.0, 1008.0),
    "a3": (841.89, 1190.55),
}

# Note patterns metadata
STYLE_METADATA = {
    "blank": {
        "id": "blank",
        "name": "Blank",
        "code": "blank",
        "key": "1",
    },
    "lines": {
        "id": "lines",
        "name": "Lined",
        "code": "lines",
        "key": "2",
    },
    "grid": {
        "id": "grid",
        "name": "Grid",
        "code": "grid",
        "key": "3",
    },
    "dots": {
        "id": "dots",
        "name": "Dot Grid",
        "code": "dots",
        "key": "4",
    },
}

STYLE_KEY_MAP = {
    "1": "blank",
    "2": "lines",
    "3": "grid",
    "4": "dots",
    "blank": "blank",
    "lines": "lines",
    "line": "lines",
    "grid": "grid",
    "dots": "dots",
    "dot": "dots",
    # Legacy / alias compatibility
    "en_blanco": "blank",
    "lineas": "lines",
    "cuadricula": "grid",
    "puntos": "dots",
}

DEFAULT_PAPER_SIZE = "a4"
DEFAULT_OUTPUT_DIR = "handouts"
DEFAULT_MARGIN = 40.0
DEFAULT_STEP = 14.0  # ~4.94 mm
DEFAULT_SEPARATION = 10.0
DEFAULT_PAGE_NUMBERS = True
DEFAULT_PAGE_NUMBER_FORMAT = "total"  # "total" (1 / N) or "simple" (1)
DEFAULT_GUTTER_MARGIN = 0.0
BINDER_GUTTER_POINTS = 30.0  # ~10.6 mm for ring binders (ISO 838 standard)
SPIRAL_GUTTER_POINTS = 22.0  # ~7.8 mm for spiral / wire-o coil binding

DEFAULT_BINDING = "none"  # "none", "binder", "spiral"
DEFAULT_HOLE_GUIDES = False

BINDING_GUTTER_MAP: Dict[str, float] = {
    "none": 0.0,
    "binder": BINDER_GUTTER_POINTS,
    "spiral": SPIRAL_GUTTER_POINTS,
}

BINDING_ALIASES: Dict[str, str] = {
    "none": "none",
    "sin": "none",
    "ninguna": "none",
    "off": "none",
    "binder": "binder",
    "ring": "binder",
    "rings": "binder",
    "archivador": "binder",
    "anillas": "binder",
    "anelas": "binder",
    "spiral": "spiral",
    "espiral": "spiral",
    "wire-o": "spiral",
    "wireo": "spiral",
    "coil": "spiral",
    "canutillo": "spiral",
}

COVER_TEMPLATES = [
    "atelier",
    "george",
    "monograph",
    "bauhaus",
    "nineteen00s",
    "nineteen10s",
    "twenties",
    "thirties",
    "forties",
    "fifties",
    "sixties",
    "seventies",
    "eighties",
    "nineties",
    "twothousands",
    "twenty10s",
    "twentytwenties",
    "spring",
    "summer",
    "autumn",
    "winter",
    "polo",
    "equestrian",
    "natural",
    "academic_green",
    "academic_teal",
    "academic_wave",
    "composition",
    "comp_blue",
    "comp_coral",
    "comp_amber",
    "comp_morris",
    "comp_ukiyoe",
    "comp_flora",
    "comp_pastoral",
    "comp_marbled",
    # Scientific & Physics Notebooks (AI Illustrated)
    "biophysics_ml",
    "atmospheric_chaos",
    "fortran_materials",
    "nuclear_particles",
    "solid_state",
    "atomic_physics",
    "circuits_instrumentation",
    # Scientific & Physics Notebooks (Flat 90s Minimalist Design)
    "quantum_flat",
    "biophysics_flat",
    "complex_systems_flat",
    "materials_sim_flat",
    "solid_state_flat",
    "circuits_flat",
    "nuclear_flat",
    # Standard Editorial & Iconic Notebooks (New Creative Line)
    "penguin",
    "gallimard",
    "oxford_press",
    "cahier",
    "midori",
    "blueprint",
    "celestial",
    "field_notes",
]

COVER_TEMPLATE_ALIASES: Dict[str, str] = {
    # Standard Editorial & Iconic Notebooks
    "penguin": "penguin",
    "penguin_classics": "penguin",
    "triband": "penguin",
    "orange_classic": "penguin",
    "gallimard": "gallimard",
    "gallimard_blanche": "gallimard",
    "collection_blanche": "gallimard",
    "nrf": "gallimard",
    "blanche": "gallimard",
    "oxford_press": "oxford_press",
    "oxford": "oxford_press",
    "clarendon": "oxford_press",
    "cambridge": "oxford_press",
    "academic_press": "oxford_press",
    "cahier": "cahier",
    "cahier_ecolier": "cahier",
    "ecolier": "cahier",
    "seyes": "cahier",
    "french_notebook": "cahier",
    "midori": "midori",
    "midori_md": "midori",
    "japanese_minimal": "midori",
    "japanese_minimalist": "midori",
    "wabi_sabi": "midori",
    "blueprint": "blueprint",
    "cyanotype": "blueprint",
    "drafting": "blueprint",
    "architectural": "blueprint",
    "celestial": "celestial",
    "star_atlas": "celestial",
    "harmonia": "celestial",
    "uranometria": "celestial",
    "astronomy": "celestial",
    "field_notes": "field_notes",
    "fieldnotes": "field_notes",
    "kraft_field": "field_notes",
    "industrial_notes": "field_notes",
    "expedition": "field_notes",
    "utilitarian": "field_notes",
    # Composition Books & Traditional Notebooks
    "composition": "composition",
    "compbook": "composition",
    "composition_book": "composition",
    "comp_classic": "composition",
    "marble_bw": "composition",
    "cuaderno": "composition",
    "compo": "composition",
    "comp_blue": "comp_blue",
    "comp_ocean": "comp_blue",
    "comp_wave": "comp_blue",
    "academic_wave": "comp_blue",
    "suminagashi": "comp_blue",
    "ocean_wave": "comp_blue",
    "academic_navy": "comp_blue",
    "academic_burgundy": "comp_blue",
    "comp_coral": "comp_coral",
    "comp_terracotta": "comp_coral",
    "comp_slate": "comp_coral",
    "academic_teal": "comp_coral",
    "ebru": "comp_coral",
    "bubble": "comp_coral",
    "academic_ebru": "comp_coral",
    "academic_stone": "comp_coral",
    "academic_blue": "comp_coral",
    "comp_amber": "comp_amber",
    "comp_gold": "comp_amber",
    "comp_onyx": "comp_amber",
    "academic_green": "comp_amber",
    "academic": "comp_amber",
    "peacock": "comp_amber",
    "florentine": "comp_amber",
    "academic_peacock": "comp_amber",
    "academic_yellow": "comp_amber",
    "comp_morris": "comp_morris",
    "morris": "comp_morris",
    "strawberry_thief": "comp_morris",
    "william_morris": "comp_morris",
    "botanical": "comp_morris",
    "comp_ukiyoe": "comp_ukiyoe",
    "ukiyoe": "comp_ukiyoe",
    "japanese": "comp_ukiyoe",
    "sakura": "comp_ukiyoe",
    "woodblock": "comp_ukiyoe",
    "comp_flora": "comp_flora",
    "flora": "comp_flora",
    "still_life": "comp_flora",
    "dutch_flora": "comp_flora",
    "bouquet": "comp_flora",
    "baroque_flora": "comp_flora",
    "comp_pastoral": "comp_pastoral",
    "pastoral": "comp_pastoral",
    "landscape": "comp_pastoral",
    "oil_landscape": "comp_pastoral",
    "romantic_landscape": "comp_pastoral",
    "comp_marbled": "comp_marbled",
    "marbled": "comp_marbled",
    "florentine_stone": "comp_marbled",
    "ebru_stone": "comp_marbled",
    "college": "composition",
    "collegeruled": "composition",
    "college_ruled": "composition",
    "vintage_college": "composition",
    "swirl": "composition",
    "marble_grey": "composition",
    # Classics
    "atelier": "atelier",
    "zara": "atelier",
    "zarahome": "atelier",
    "george": "george",
    "jfk": "george",
    "executive": "george",
    "monograph": "monograph",
    "bauhaus": "bauhaus",
    # Decades 20th Century
    "nineteen00s": "nineteen00s",
    "1900s": "nineteen00s",
    "1900": "nineteen00s",
    "00s": "nineteen00s",
    "artnouveau": "nineteen00s",
    "bellepoque": "nineteen00s",
    "turnofcentury": "nineteen00s",
    "nineteen10s": "nineteen10s",
    "1910s": "nineteen10s",
    "1910": "nineteen10s",
    "10s": "nineteen10s",
    "edwardian": "nineteen10s",
    "telegraph": "nineteen10s",
    "twenties": "twenties",
    "20s": "twenties",
    "1920s": "twenties",
    "1920": "twenties",
    "artdeco": "twenties",
    "gatsby": "twenties",
    "thirties": "thirties",
    "30s": "thirties",
    "1930s": "thirties",
    "1930": "thirties",
    "streamline": "thirties",
    "forties": "forties",
    "40s": "forties",
    "1940s": "forties",
    "1940": "forties",
    "typewriter": "forties",
    "postwar": "forties",
    "fifties": "fifties",
    "50s": "fifties",
    "1950s": "fifties",
    "1950": "fifties",
    "midcentury": "fifties",
    "pelican": "fifties",
    "sixties": "sixties",
    "60s": "sixties",
    "1960s": "sixties",
    "1960": "sixties",
    "swiss": "sixties",
    "helvetica": "sixties",
    "seventies": "seventies",
    "70s": "seventies",
    "1970s": "seventies",
    "1970": "seventies",
    "retro": "seventies",
    "apollo": "seventies",
    "eighties": "eighties",
    "80s": "eighties",
    "1980s": "eighties",
    "1980": "eighties",
    "memphis": "eighties",
    "synthwave": "eighties",
    "nineties": "nineties",
    "90s": "nineties",
    "1990s": "nineties",
    "1990": "nineties",
    "grunge": "nineties",
    "lookbook": "nineties",
    "zine": "nineties",
    # Decades 21st Century
    "twothousands": "twothousands",
    "2000s": "twothousands",
    "2000": "twothousands",
    "y2k": "twothousands",
    "noughties": "twothousands",
    "twenty10s": "twenty10s",
    "2010s": "twenty10s",
    "2010": "twenty10s",
    "flatdesign": "twenty10s",
    "startup": "twenty10s",
    "twentytwenties": "twentytwenties",
    "2020s": "twentytwenties",
    "2020": "twentytwenties",
    "neubrutalism": "twentytwenties",
    "contemporary": "twentytwenties",
    "ai_era": "twentytwenties",
    # Seasons
    "spring": "spring",
    "primavera": "spring",
    "vernal": "spring",
    "summer": "summer",
    "verano": "summer",
    "estio": "summer",
    "autumn": "autumn",
    "otono": "autumn",
    "otonno": "autumn",
    "fall": "autumn",
    "winter": "winter",
    "invierno": "winter",
    "hiemal": "winter",
    # Ralph Lauren
    "polo": "polo",
    "ralph": "polo",
    "ralphlauren": "polo",
    "ralph_lauren": "polo",
    "rl_polo": "polo",
    "preppy": "polo",
    "equestrian": "equestrian",
    "ecuestre": "equestrian",
    "rl_equestrian": "equestrian",
    "saddlery": "equestrian",
    # Nature
    "natural": "natural",
    "forest": "natural",
    "verde": "natural",
    "nature": "natural",
    # Scientific & Physics Notebooks (AI Illustrated)
    "biophysics_ml": "biophysics_ml",
    "biophysics": "biophysics_ml",
    "biofisica": "biophysics_ml",
    "biofisica_ml": "biophysics_ml",
    "alphafold": "biophysics_ml",
    "neural_bio": "biophysics_ml",
    "atmospheric_chaos": "atmospheric_chaos",
    "atmospheric": "atmospheric_chaos",
    "atmosferica": "atmospheric_chaos",
    "complex_systems": "atmospheric_chaos",
    "sistemas_complejos": "atmospheric_chaos",
    "chaos": "atmospheric_chaos",
    "lorenz": "atmospheric_chaos",
    "fortran_materials": "fortran_materials",
    "fortran": "fortran_materials",
    "materiales": "fortran_materials",
    "materials_sim": "fortran_materials",
    "computational_materials": "fortran_materials",
    "simulacion_materiales": "fortran_materials",
    "simulacion_fisica_materiales": "fortran_materials",
    "f77": "fortran_materials",
    "f90": "fortran_materials",
    "nuclear_particles": "nuclear_particles",
    "nuclear": "nuclear_particles",
    "particulas": "nuclear_particles",
    "particle_physics": "nuclear_particles",
    "cern": "nuclear_particles",
    "lhc": "nuclear_particles",
    "feynman": "nuclear_particles",
    "solid_state": "solid_state",
    "estado_solido": "solid_state",
    "solido": "solid_state",
    "condensed_matter": "solid_state",
    "brillouin": "solid_state",
    "fermi_surface": "solid_state",
    "atomic_physics": "atomic_physics",
    "atomic": "atomic_physics",
    "atomica": "atomic_physics",
    "quantum_atomic": "atomic_physics",
    "spectroscopy": "atomic_physics",
    "rydberg": "atomic_physics",
    "mecanica_cuantica_3": "atomic_physics",
    "mecanica_cuantica": "atomic_physics",
    "cuantica_3": "atomic_physics",
    "cuantica": "atomic_physics",
    "quantum_3": "atomic_physics",
    "quantum3": "atomic_physics",
    "quantum_mechanics": "atomic_physics",
    "quantum_mechanics_3": "atomic_physics",
    "quantum_mechanics_iii": "atomic_physics",
    "mq3": "atomic_physics",
    "materials_physics_simulation": "fortran_materials",
    "physics_of_complex_systems": "atmospheric_chaos",
    "physics_complex_systems": "atmospheric_chaos",
    "fundamentals_of_electronic_instrumentation": "circuits_instrumentation",
    "fundamentals_electronic_instrumentation": "circuits_instrumentation",
    "electronic_instrumentation": "circuits_instrumentation",
    "solid_state_physics": "solid_state",
    "nuclear_and_particle_physics": "nuclear_particles",
    "nuclear_particle_physics": "nuclear_particles",
    "circuits_instrumentation": "circuits_instrumentation",
    "circuits": "circuits_instrumentation",
    "instrumentacion": "circuits_instrumentation",
    "fundamentos_instrumentacion": "circuits_instrumentation",
    "fundamentos_instrumentacion_electronica": "circuits_instrumentation",
    "instrumentacion_electronica": "circuits_instrumentation",
    "opamps": "circuits_instrumentation",
    "electronica": "circuits_instrumentation",
    "filters": "circuits_instrumentation",
    "adc_dac": "circuits_instrumentation",
    # Scientific & Physics Notebooks (Flat 90s Minimalist Design)
    "quantum_flat": "quantum_flat",
    "quantum_mechanics_flat": "quantum_flat",
    "quantum_mechanics_3_flat": "quantum_flat",
    "quantum_mechanics_iii_flat": "quantum_flat",
    "mecanica_cuantica_flat": "quantum_flat",
    "mecanica_cuantica_3_flat": "quantum_flat",
    "cuantica_flat": "quantum_flat",
    "cuantica3_flat": "quantum_flat",
    "mq3_flat": "quantum_flat",
    "atomic_flat": "quantum_flat",
    "biophysics_flat": "biophysics_flat",
    "biofisica_flat": "biophysics_flat",
    "bio_flat": "biophysics_flat",
    "alphafold_flat": "biophysics_flat",
    "complex_systems_flat": "complex_systems_flat",
    "physics_of_complex_systems_flat": "complex_systems_flat",
    "physics_complex_systems_flat": "complex_systems_flat",
    "sistemas_complejos_flat": "complex_systems_flat",
    "chaos_flat": "complex_systems_flat",
    "atmospheric_flat": "complex_systems_flat",
    "atmosferica_flat": "complex_systems_flat",
    "materials_sim_flat": "materials_sim_flat",
    "materials_physics_simulation_flat": "materials_sim_flat",
    "simulacion_materiales_flat": "materials_sim_flat",
    "simulacion_fisica_materiales_flat": "materials_sim_flat",
    "fortran_flat": "materials_sim_flat",
    "materiales_flat": "materials_sim_flat",
    "solid_state_flat": "solid_state_flat",
    "solid_state_physics_flat": "solid_state_flat",
    "estado_solido_flat": "solid_state_flat",
    "solido_flat": "solid_state_flat",
    "condensed_matter_flat": "solid_state_flat",
    "circuits_flat": "circuits_flat",
    "fundamentals_of_electronic_instrumentation_flat": "circuits_flat",
    "fundamentals_electronic_instrumentation_flat": "circuits_flat",
    "electronic_instrumentation_flat": "circuits_flat",
    "circuitos_flat": "circuits_flat",
    "instrumentacion_flat": "circuits_flat",
    "fundamentos_instrumentacion_flat": "circuits_flat",
    "electronica_flat": "circuits_flat",
    "nuclear_flat": "nuclear_flat",
    "nuclear_and_particle_physics_flat": "nuclear_flat",
    "nuclear_particle_physics_flat": "nuclear_flat",
    "particulas_flat": "nuclear_flat",
    "nuclear_particles_flat": "nuclear_flat",
    "particle_physics_flat": "nuclear_flat",
}

DEFAULT_DUPLEX = False
DEFAULT_STUDY_HEADER = False
DEFAULT_LAYOUT = "1-up"  # "1-up" or "2-up"
DEFAULT_GRAYSCALE = False
DEFAULT_COVER_MODE = "generate"  # "generate" (default), "clean_first", "none"
DEFAULT_COVER_TEMPLATE = "atelier"

